const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file:///'+path.resolve(process.env.TEST_HTML||'src/index.html').replaceAll('\\','/'));
 await page.evaluate(()=>{loadDemo();save();renderAll();});
 await page.click('#startGuide');await page.click('#guideNext');await page.click('#guideNext');
 await page.selectOption('#preMode','day');await page.locator('#preCal .dcell').first().click();
 const first=await page.evaluate(()=>({sid:ui.preStaff,ds:ui.preDay,code:getCycle(ui.curStart).fixed[ui.preStaff][ui.preDay].code}));assert.equal(first.code,'OF');
 await page.selectOption('#preMode','person');assert.equal(await page.locator('#preCal .dcell .mk').first().innerText(),'休');
 await page.click('#preSeg [data-code="W8"]');await page.locator('#preCal .dcell').nth(1).click();
 await page.selectOption('#preMode','day');await page.selectOption('#preDaySel',await page.evaluate(()=>addDays(ui.curStart,1)));assert.match(await page.locator('#preCal .dcell').first().innerText(),/8時/);
 await page.click('#preSeg [data-code=""]');await page.locator('#preCal .dcell').first().click();
 assert.equal(await page.evaluate(()=>getCycle(ui.curStart).fixed[ui.preStaff][ui.preDay]),undefined);
 await page.click('#guideNext');await page.click('#guideNext');assert.equal(await page.locator('#reviewBody [data-sid]').count(),28);
 await page.click('#reviewDay');assert.equal(await page.locator('#reviewBody [data-sid]').count(),await page.evaluate(()=>state.staff.length));
 await page.locator('#reviewBody [data-sid]').first().click();assert.equal(await page.locator('#page-sched').getAttribute('class'),'page active');
 const generated=await page.evaluate(()=>{const r=solve(ui.curStart,{iter:2000});applySolution(r);return !!r;});assert(generated);
 await page.click('[data-page="review"]');await page.click('#reviewPerson');
 const before=await page.evaluate(()=>JSON.stringify(getCycle(ui.curStart).fixed));await page.waitForTimeout(350);await page.reload();assert.equal(await page.evaluate(()=>JSON.stringify(getCycle(ui.curStart).fixed)),before);
 await page.click('[data-page="review"]');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'review-mobile.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.click('[data-page="pre"]');await page.selectOption('#preMode','day');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'input-mobile.png',fullPage:true});
 await page.click('#preSeg [data-code="TSU"]');await page.locator('#preCal .dcell').first().click();await page.click('#tsuOk');
 assert.equal(await page.evaluate(()=>getCycle(ui.curStart).fixed[ui.preStaff][ui.preDay].code),'TSU');
 await page.evaluate(()=>{const c=getCycle(ui.curStart);c.cells[ui.preStaff][ui.preDay].code='OF';ui.reviewTarget=ui.preStaff;ui.reviewMode='person';switchTab('review');});
 assert.match(await page.locator('#reviewBody').innerText(),/不一致 1件/);
 await page.evaluate(()=>buildPrint());assert(await page.locator('#printRoot table').count());
 const download=page.waitForEvent('download');await page.evaluate(()=>document.querySelector('#btnXlsx').click());assert.match((await download).suggestedFilename(),/xlsx$/);
 await page.evaluate(()=>{state.staff=[];renderAll();switchTab('review');});assert.match(await page.locator('#reviewBody').innerText(),/未登録/);
 assert.deepEqual(errors,[]);console.log('PASS: guide, shared person/day inputs, fixed work, erase, review views, edit jump, solver, persistence, mobile width, empty staff, no JS errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
